### ISSUE TITLE
Do not close issue until this works

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/get_entropy#1]
Still tons of problems with this file. 

1. Load
2. Call BrainBeats
3. Select "Extract EEG and HRV features from cont data"
4. Select ECG channel
5. Select no for cleaning EEG data
6. Select HRV features only
(see screen capture)
[sub-024_task-Post1_eeg..set.zip](https://github.com/amisepa/get_entropy/files/11436704/sub-024_task-Post1_eeg.set.zip)
![Screen Shot 2023-05-09 at 12 50 03 PM](https://github.com/amisepa/get_entropy/assets/1872705/fa893782-fe9a-45f3-a0ab-123d2214fdbc)

**Comment by arnodelorme** [comment]
Issue when trying to scroll peaks

![Screen Shot 2023-05-09 at 12 50 27 PM](https://github.com/amisepa/get_entropy/assets/1872705/8a131223-e899-4a0e-8f9e-c0c486c573bb)

**Comment by arnodelorme** [comment]
Issue when simply calling the function above

![Screen Shot 2023-05-09 at 12 47 32 PM](https://github.com/amisepa/get_entropy/assets/1872705/aaab129e-2ce4-44cd-ae71-8984e886a520)

**Comment by arnodelorme** [comment]
An my fix for the area function so it does not crash (line 235 of pop_brainbeats) is probably wrong.

**Comment by amisepa** [comment]
I'm still working on the Feature mode. 
But the area plot works great for me. it shouldn't be [mfe;mfe], it should be 
area(scales,mfe,'FaceColor',[0.6350 0.0780 0.1840],'FaceAlpha',.7);

**Comment by amisepa** [comment]
how did it happen the scrolling error? after scrolling out of bounds or immediately?

**Comment by arnodelorme** [comment]
Yes crashes for me because

Scales is of size 2x30
And mfe is of size 1x30

**Comment by arnodelorme** [comment]
It does not scroll on Mac. It happens when you click on the bar below the plot and try to scroll.

**Comment by amisepa** [comment]
I've got a merge conflict :/

I'm plotting the whole series without scrolling now it's simpler. 

Which sample dataset are you using? 1 or 2? because I'm not getting 2x30 for scales with sample_dataset2
